import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {readCoarseIndex} from '../scripts/vision_index_reader.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),manifest=JSON.parse(fs.readFileSync(path.join(root,'runtime/vision-coarse-index.json'),'utf8')),binary=fs.readFileSync(path.join(root,'runtime/vision-coarse-index.bin')),audit=JSON.parse(fs.readFileSync(path.join(root,'data/descriptor-audit-summary.json'),'utf8'));
test('binary manifest and dimensions',()=>{const values=readCoarseIndex(manifest,binary);assert.equal(manifest.referenceCount,7180);assert.equal(manifest.dimension,216);assert.equal(values.length,7180*216);assert.equal(new Set(manifest.references.map(x=>x.refId)).size,7180)});
test('corrupted binary is rejected',()=>assert.throws(()=>readCoarseIndex(manifest,binary.subarray(0,-4)),/truncated/));
test('descriptor provenance',()=>{assert.equal(manifest.descriptorSourceCommit,'b63435e2796e0bf4f5118fcc8106a8eec44d1d2f');assert.equal(manifest.descriptorSourceSha256,'306eafe4decdcce26287683bc581cd8ca24a0c2f58cd299873b093942127a14a')});
test('shortlist recall qualification',()=>{assert.ok(audit.recallAtK['24']>=.999);assert.ok(audit.sampleSize>=553)});
test('portrait landscape and side coverage',()=>{assert.ok(audit.orientation.portrait);assert.ok(audit.orientation.landscape);assert.ok(audit.orientation.leaderFrontBack);assert.equal(manifest.references.filter(x=>x.side==='back').length,461);for(const cardId of ['swu-echo-caverns-base-423862ecfaa0','swu-forward-command-post-base-56c5b50e4ce2'])assert.deepEqual(new Set(manifest.references.filter(x=>x.cardId===cardId).map(x=>x.side)),new Set(['front','back']));assert.equal(audit.orientation.landscapeCases.length,4);assert.ok(audit.orientation.landscapeCases.every(x=>x.rank<=4))});
test('required shared groups remain coherent',()=>{const cases=audit.detailedRecognitionAudit.requiredSharedCases;assert.equal(cases.length,6);assert.ok(cases.every(x=>x.minDetailedSimilarity>=.90));assert.deepEqual(new Set(cases.map(x=>x.cardName.split(' — ')[0])),new Set(['Red Three','Battle Droid','Clone Trooper']))});
test('no exact robust promotion',()=>{assert.equal(audit.detailedRecognitionAudit.candidates,4775);assert.equal(Object.values(audit.detailedRecognitionAudit.counts).reduce((a,b)=>a+b,0),4775)});
