import fs from 'node:fs';import path from 'node:path';import {performance} from 'node:perf_hooks';
import {ROOT,browserPage,readJson} from './vision_build_common.mjs';
const canonical=readJson('runtime/canonical-vision-index.json'),groups=readJson('data/recognition-groups.json'),families=readJson('data/visual-families.json'),faces=readJson('data/faces.json'),cards=readJson('data/cards.json');
const canonicalByFamily=new Map(canonical.map(x=>[x.visualFamilyId,x])),familyById=new Map(families.map(x=>[x.visualFamilyId,x])),faceByRef=new Map(faces.map(x=>[x.refId,x]));
const byCardSide=new Map();for(const ref of canonical){const key=`${ref.cardId}\x1f${ref.side}`;if(!byCardSide.has(key))byCardSide.set(key,[]);byCardSide.get(key).push(ref)}
const candidateJobs=[];for(const refs of byCardSide.values())for(const ref of refs){const group=groups.find(x=>x.visualFamilyId===ref.visualFamilyId);if(group.classification==='exact_candidate')candidateJobs.push({refId:ref.refId,imageUrl:ref.imageUrl,others:refs.filter(x=>x.visualFamilyId!==ref.visualFamilyId).map(x=>({refId:x.refId,imageUrl:x.imageUrl}))})}
const sharedJobs=groups.filter(x=>x.classification==='shared').map(group=>({recognitionGroupId:group.recognitionGroupId,refs:familyById.get(group.visualFamilyId).refIds.map(refId=>({refId,imageUrl:faceByRef.get(refId).imageUrl}))}));
const {browser,page}=await browserPage(),started=performance.now();let candidateResults,sharedResults;
try{
  candidateResults=await page.evaluate(async jobs=>{let cursor=0;const out=new Array(jobs.length);async function descriptor(url){return globalThis.TCGateDescriptor.descriptorFromUrl(url)}async function worker(){while(true){const i=cursor++;if(i>=jobs.length)return;const job=jobs[i],base=await descriptor(job.imageUrl);let best=-1,bestRefId=null;for(const other of job.others){const value=globalThis.TCGateDescriptor.compareDescriptors(base,await descriptor(other.imageUrl)).total;if(value>best){best=value;bestRefId=other.refId}}out[i]={refId:job.refId,bestOtherScore:best,bestOtherRefId:bestRefId}}}await Promise.all(Array.from({length:12},worker));return out},candidateJobs);
  sharedResults=await page.evaluate(async jobs=>{let cursor=0;const out=new Array(jobs.length);async function worker(){while(true){const i=cursor++;if(i>=jobs.length)return;const job=jobs[i],descriptors=[];for(const ref of job.refs)descriptors.push([ref.refId,await globalThis.TCGateDescriptor.descriptorFromUrl(ref.imageUrl)]);let min=1;for(let a=0;a<descriptors.length;a++)for(let b=a+1;b<descriptors.length;b++)min=Math.min(min,globalThis.TCGateDescriptor.compareDescriptors(descriptors[a][1],descriptors[b][1]).total);out[i]={recognitionGroupId:job.recognitionGroupId,minDetailedSimilarity:min,refIds:job.refs.map(x=>x.refId)}}}await Promise.all(Array.from({length:12},worker));return out},sharedJobs);
}finally{await browser.close()}
const classes={ROBUSTLY_SEPARATED_CANDIDATE:0,CLOSE_CANDIDATE:0,AMBIGUOUS_CANDIDATE:0};for(const result of candidateResults){result.auditClass=result.bestOtherScore<.90?'ROBUSTLY_SEPARATED_CANDIDATE':result.bestOtherScore<.97?'CLOSE_CANDIDATE':'AMBIGUOUS_CANDIDATE';classes[result.auditClass]++}
const anomalies=sharedResults.filter(x=>x.minDetailedSimilarity<.90).sort((a,b)=>a.minDetailedSimilarity-b.minDetailedSimilarity),cardById=new Map(cards.map(x=>[x.id,x])),groupById=new Map(groups.map(x=>[x.recognitionGroupId,x]));
const requiredNames=new Set(['Red Three — Unstoppable','Battle Droid','Clone Trooper']);
const requiredSharedCases=sharedResults.filter(result=>{const group=groupById.get(result.recognitionGroupId),card=cardById.get(group.cardId),name=[card.name,card.subtitle].filter(Boolean).join(' — ');result.cardName=name;return requiredNames.has(name)});
const summaryPath=path.join(ROOT,'data/descriptor-audit-summary.json'),summary=JSON.parse(fs.readFileSync(summaryPath,'utf8'));summary.detailedRecognitionAudit={thresholds:{robustlySeparatedBelow:.90,closeBelow:.97,ambiguousAtOrAbove:.97},counts:classes,candidates:candidateResults.length,sharedGroups:sharedResults.length,sharedAnomalyThreshold:.90,sharedAnomalies:anomalies,requiredSharedCases,durationMilliseconds:Number((performance.now()-started).toFixed(3))};fs.writeFileSync(summaryPath,JSON.stringify(summary,null,2)+'\n');
console.log(JSON.stringify({candidateCounts:classes,candidates:candidateResults.length,sharedGroups:sharedResults.length,sharedAnomalies:anomalies.length,durationMilliseconds:summary.detailedRecognitionAudit.durationMilliseconds}));
